services:
  frontend:
    build:
      context: ./frontend
    ports:
      - "5173:5173"
    depends_on:
      - backend
    environment:
      - VITE_HOST=0.0.0.0
 
  backend:
    build:
      context: ./backend
    ports:
      - "3000:3000"
    depends_on:
      - database
    environment:
      - DATABASE_URL=mysql://user:password@database:3306/dbname
 
  database:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: train
      MYSQL_ROOT_PASSWORD: rootpassword
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
 
volumes:
  mysql_data: